Assignment 3
Sky322/haxeFlixel-Practice pull request #2
Opened 2020-04-15 15:15 UTC by Sky322

2020-04-15 15:21 UTC, Sky322 commented
added a win condition which is just a orange square that changes location and fail condition is the fireballs. Also controls are either WASD or arrow keys

2020-04-16 02:43 UTC, SamBumgardner requested changes
There's one issue that prevents neko builds, so I'd like that fixed before merging. I leave the other issue to fix at your discretion.

Other than that, it looked good. I liked dodging between fireballs quite a bit! 
Will check back in after it's fixed to give final approval.

2020-04-16 02:43 UTC, SamBumgardner commented on source/PlayState.hx
> +import js.lib.webassembly.Global;
I don't think this is used anywhere, and including it prevents the game from building to the neko target via `lime test neko`

I'd like this removed before merging, please.

2020-04-16 02:43 UTC, SamBumgardner commented on source/PlayState.hx
> +		ifWon();
I don't think you meant to put these function calls inside your fireball object-wrapping loop. As-is, they get called way more often than they need to.

2020-04-25 01:19 UTC, merged